language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags
notifications:
  email: false
sudo: false
after_success:
- julia -e 'if VERSION >= v"0.7-"; using Pkg; else; cd(Pkg.dir("CouenneNL")); end; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
